# Generated by Django 3.2 on 2023-07-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
